name: mobile_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'



#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  connectivity_plus: ^6.0.3
  lottie: ^3.1.0 # OR RIVE

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

  # Firebase
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  google_fonts: ^6.2.1
  firebase_database: ^10.0.8
  cloud_firestore: ^4.9.0
  firebase_auth: ^4.2.1
  image_picker: ^0.8.7+3
  google_sign_in: ^6.2.2
  uuid: ^4.5.1
  provider: ^6.0.5
  socket_io_client: ^3.0.2


  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/facebook-icon.png
    - assets/logos/google-icon.png
    - assets/logos/t-store-splash-logo-black.png
    - assets/logos/t-store-splash-logo-white.png
    - assets/images/animations/sammy-line-come-back-later.png
    - assets/images/animations/sammy-line-man-receives-a-mail.png
    - assets/images/animations/sammy-line-sale.png
    - assets/images/animations/sammy-line-success.png
    - assets/images/animations/sammy-line-travel-backpack-with-passport-and-air-ticket.gif
    - assets/images/animations/sammy-line-workout.gif
    - assets/images/animations/141594-animation-of-docer.json
    - assets/icons/categories/icons8-bowling-64.png
    - assets/icons/categories/icons8-cosmetics-64.png
    - assets/icons/categories/icons8-dining-chair-64.png
    - assets/icons/categories/icons8-dog-heart-64.png
    - assets/icons/categories/icons8-school-uniform-64.png
    - assets/icons/categories/icons8-shoes-64.png
    - assets/icons/categories/icons8-smartphone-64.png
    - assets/icons/categories/icons8-sparkling-diamond-64.png
    - assets/icons/categories/icons8-sparkling-diamond-64.png
    - assets/icons/categories/icons8-tailors-dummy-64.png
    - assets/icons/categories/icons8-wooden-toy-car-50.png
    - assets/images/on_boarding_images/sammy-line-delivery.gif
    - assets/images/on_boarding_images/sammy-line-no-connection.gif
    - assets/images/on_boarding_images/sammy-line-searching.gif
    - assets/images/on_boarding_images/sammy-line-shopping.gif
    - assets/images/products/
  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800